sudo: required
language: julia
notifications:
  email: false
before_install:
- sudo apt-get install python-pip
- python --version
- pip --version
- sudo pip install --upgrade pip
- sudo pip install matplotlib
script:
- date
- julia -e 'cd("test"); include("runtests.jl");'
