sudo: required
language: julia
notifications:
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_5b34a3804359_key -iv $encrypted_5b34a3804359_iv
  -in .id_rsa_peelcb.enc -out .id_rsa_peelcb -d
- sudo apt-get install python-matplotlib
script:
- date
- julia -e 'include("test/runtests.jl");'
after_success:
- julia -e 'include("benchmark/perftest.jl")'
- chmod 600 .id_rsa_peelcb
- eval "$(ssh-agent)"
- ssh-add .id_rsa_peelcb
- git remote add deploy git@github.com:christianpeel/LLLplus.jl.git
- git config user.email "build@travis"
- git config user.name "Travis build"
- ls -la benchmark
- git add benchmark/*.png
- git status
- git commit -m "Performance results via Travis\n[skip ci]"
- git push deploy
