#before_install:
#  - export TZ=America/Los_Angeles
sudo: required
language: julia
notifications:
  email: false
before_install:
  - sudo apt-get install python-matplotlib
script:
  - date
  - julia -e 'include("test/runtests.jl");'
after_success:
  - julia -e 'include("benchmark/perftest.jl")'
  - openssl aes-256-cbc -K $encrypted_5b34a3804359_key -iv $encrypted_5b34a3804359_iv -in .id_rsa_peelcb.enc -out .id_rsa_peelcb -d
  - chmod 600 .id_rsa_peelcb
  - ssh-add .id_rsa_peelcb
  - git remote add deploy git@github.com:christianpeel/LLLplus.jl.git
  - ls -la .id*
  - ls -la benchmark
  - git add benchmark/*.png
  - git status
  - git commit -m "Performance results\n[skip ci]"
  - git push deploy
