#before_install:
#  - export TZ=America/Los_Angeles
language: julia
notifications:
    email: false
script:
  - date
  - julia -e 'include("test/runtests.jl"); include("benchmark/perftest.jl")'
  - ls -la benchmark
  - git add benchmark/*.png
  - git commit -m "Performance results\n[skip ci]"
  - git push
